### ISSUE TITLE
[IONIC] IOS Spacebar issue

### ISSUE THREAD

**Issue by sharanu639** [demjhonsilver/mirax-player#2]
Hi ,
      The video gets played when i have a page with a video component and a comment section on a single page and use the space bar in the comment box. When a user enters a comment using the space bar, then the space bar triggers the video to resume/pause. Is there a way to disable the space bar?.

**Comment by demjhonsilver** [comment]
I'm sorry if you face that kind of issue when you hit the space bar. Yes there's another way, it has been disabled for pure spacebar key issue but it has been replaced into 2 shortcut keys with CTRL + Spacebar.  Thanks for reporting this issue.` 
    document.addEventListener('keydown', function(event) {
      // Check if the pressed key ctrl and space bar
      if (event.code === 'Space') {
        // Prevent the default action of scrolling
        event.preventDefault();
        if (event.ctrlKey) { // CTRL + SPACEBAR
          // Call the same function that you use for the play button
          playerButton();
        }
      }
    });
    `
